options {
  directory "/var/bind";

	listen-on { any; };
	listen-on-v6 { any; };

  pid-file "/var/run/named/named.pid";

  allow-recursion { none; };
  recursion no;

  allow-transfer { any; };
};

logging {
    channel stdout_errors {
        stderr;
        severity error;

        print-category yes;
        print-severity yes;
        print-time yes;
    };

    category default { stdout_errors; };
};

zone "btidor.dev" {
  type primary;
  file "btidor.dev.signed";
};

zone "ccpa.party" {
  type primary;
  file "ccpa.party.signed";
};

zone "tidor.net" {
  type primary;
  file "tidor.net.signed";
};
