name: Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "17 17 * * 2"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt update && sudo apt install -y age bind9
      - run: make && make check && rm .key
        env:
          AGE_KEY: ${{ secrets.AGE_KEY }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
